a_core/urls.py
from django.contrib import admin
from django.urls import path
from a_posts.views import *

urlpatterns = [
    #path('page-name', html_page_name, name='page-name')
    #path('',name=''),
    path('admin/', admin.site.urls),
    path('', home_view),
    path('monster/create/', create_monster_view, name='create-monster'),
    path('view/monsters/', view_all_monsters, name='view-all-monsters'),
    path('monster/create/manual-input-form/', manual_input_form_view, name='manual-input-form'),
    path('monster/create/automatic-input-form/', automatic_input_form_view, name='automatic-input-form'),
    path('monster/create/manual-data-entered/', manual_data_entered_view, name='manual-data-entered'),
    path('monster/create/automatic-data-entered/', automatic_data_entered_view, name='automatic-data-entered'),
]

a_posts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User, AbstractBaseUser, BaseUserManager, PermissionsMixin
  # Import the User model
import uuid



class Monster(models.Model):
    INPUT_METHOD_CHOICES = [
        ('automatic', 'Automatic'),
        ('manual', 'Manual'),
    ]

    # Common fields
    name = models.CharField(max_length=255)
    size = models.CharField(max_length=20, null=True, blank=True)
    creature_type = models.CharField(max_length=20, null=True, blank=True)
    alignment = models.CharField(max_length=20, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    input_method = models.CharField(max_length=20, choices=INPUT_METHOD_CHOICES, default='manual')
    
    # Stats
    armor_class = models.IntegerField(null=True, blank=True)
    hit_points = models.PositiveIntegerField(null=True, blank=True)
    
    speed = models.CharField(max_length=50, null=True, blank=True)
    
    # Speed fields
    land_speed = models.IntegerField(null=True, blank=True)
    burrow_speed = models.IntegerField(null=True, blank=True)
    fly_speed = models.IntegerField(null=True, blank=True)
    swim_speed = models.IntegerField(null=True, blank=True)
    
    # Abilities
    strength = models.IntegerField(null=True, blank=True)
    dexterity = models.IntegerField(null=True, blank=True)
    constitution = models.IntegerField(null=True, blank=True)
    intelligence = models.IntegerField(null=True, blank=True)
    wisdom = models.IntegerField(null=True, blank=True)
    charisma = models.IntegerField(null=True, blank=True)
    
    # Saving Throws
    saving_throws = models.TextField(null=True, blank=True)
    
    # Skills
    skills = models.TextField(null=True, blank=True)
    
    # Damage Resistances and Immunities
    damage_resistances = models.TextField(null=True, blank=True)
    damage_immunities = models.TextField(null=True, blank=True)
    condition_immunities = models.TextField(null=True, blank=True)
    
    # Senses
    senses = models.TextField(null=True, blank=True)
    
    # Languages
    languages = models.TextField(null=True, blank=True)
    
    # Challenge and XP
    challenge_rating = models.DecimalField(max_digits=3, decimal_places=1, null=True, blank=True)
    experience_points = models.IntegerField(null=True, blank=True)
    
    # Special, Legendary, and Lair Actions
    special_abilities = models.TextField(null=True, blank=True)
    special_abilities_count = models.IntegerField(null=True, blank=True)
    
    # Spells
    # To-do
        
    # Actions
    actions = models.TextField(null=True, blank=True)
    
    # Extras
    raw_stat_block = models.TextField(blank=True)
    
    def __str__(self):
        return self.name


class Spell(models.Model):
    INPUT_METHOD_CHOICES = [
        ('automatic', 'Automatic'),
        ('manual', 'Manual'),
    ]

    SPELL_TYPES = [
        ('DD', 'Damage Dealing'),
        ('HL', 'Healing'),
        ('UT', 'Utility'),
        ('OT', 'Other'),
    ]
    
    MAGIC_SCHOOL_CHOICES = [
        ('abjuration', 'Abjuration'),
        ('conjuration', 'Conjuration'),
        ('divination', 'Divination'),
        ('enchantment', 'Enchantment'),
        ('evocation', 'Evocation'),
        ('illusion', 'Illusion'),
        ('necromancy', 'Necromancy'),
        ('transmutation', 'Transmutation'),
    ]
            
    # Common
    spell_name = models.CharField(max_length=100)
    spell_type = models.CharField(max_length=2, choices=SPELL_TYPES)
    input_method = models.CharField(max_length=20, choices=INPUT_METHOD_CHOICES, default='manual')
    created_at = models.DateTimeField(default=timezone.now)

    school_of_magic = models.CharField(max_length=24,choices=MAGIC_SCHOOL_CHOICES, default='')
    description = models.TextField()
    class_requirement = models.TextField(blank=True, null=True)
    effect = models.CharField(max_length=100, blank=True, null=True)
    cast_at_higher_levels = models.BooleanField(default=False)
    
    # Additional spell attributes
    casting_time = models.CharField(max_length=50, blank=True, null=True)
    spell_range = models.CharField(max_length=50, blank=True, null=True)
    spell_target = models.CharField(max_length=100, blank=True, null=True)
    spell_components = models.CharField(max_length=50, blank=True, null=True)
    spell_duration = models.CharField(max_length=50, blank=True, null=True)
    spell_classes = models.CharField(max_length=200, blank=True, null=True)
    spell_effect_description = models.TextField(blank=True, null=True)
    spell_damage_description = models.TextField(blank=True, null=True)
    spell_scaling_description = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return self.spell_name


class CharacterClass(models.Model):
    CLASS_CHOICES = [
        ('artificer', 'Artificer'),
        ('barbarian', 'Barbarian'),
        ('bard', 'Bard'),
        ('bloodhunter','Blood Hunter'),
        ('cleric', 'Cleric'),
        ('druid', 'Druid'),
        ('fighter', 'Fighter'),
        ('monk', 'Monk'),
        ('paladin', 'Paladin'),
        ('ranger', 'Ranger'),
        ('rogue', 'Rogue'),
        ('sorcerer', 'Sorcerer'),
        ('warlock', 'Warlock'),
        ('wizard', 'Wizard'),
        # Add other classes as needed
    ]

    class_name = models.CharField(max_length=50, choices=CLASS_CHOICES)
    level = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.class_name} - Level {self.level}"


class PlayerCharacter(models.Model):
    INPUT_METHOD_CHOICES = [
        ('automatic', 'Automatic'),
        ('manual', 'Manual'),
    ]
    
    RACE_CHOICES = [
        ('human', 'Human'),
        ('elf', 'Elf'),
        ('dwarf', 'Dwarf'),
        ('halfling', 'Halfling'),
        ('aarakocra', 'Aarakocra'),
        ('aasimar', 'Aasimar'),
        ('aetherborn', 'Aetherborn'),
        ('astral_elf', 'Astral Elf'),
        ('autognome', 'Autognome'),
        ('bugbear', 'Bugbear'),
        ('centaur', 'Centaur'),
        ('changeling', 'Changeling'),
        ('deep_gnome', 'Deep Gnome'),
        ('dhampir', 'Dhampir'),
        ('dragonborn', 'Dragonborn'),
        ('duergar', 'Duergar'),
        ('eladrin', 'Eladrin'),
        ('elf_ua', 'Elf/Unearthed Arcana'),
        ('fairy', 'Fairy'),
        ('firbolg', 'Firbolg'),
        ('genasi', 'Genasi'),
        ('giff', 'Giff'),
        ('gith', 'Gith'),
        ('githyanki', 'Githyanki'),
        ('githzerai', 'Githzerai'),
        ('glitchling', 'Glitchling'),
        ('gnome', 'Gnome'),
        ('goblin', 'Goblin'),
        ('goliath', 'Goliath'),
        ('grung', 'Grung'),
        ('hadozee', 'Hadozee'),
        ('half_elf', 'Half-elf'),
        ('half_orc', 'Half-orc'),
        ('harengon', 'Harengon'),
        ('hexblood', 'Hexblood'),
        ('hobgoblin', 'Hobgoblin'),
        ('hollow_one', 'Hollow One'),
        ('kalashtar', 'Kalashtar'),
        ('kender', 'Kender'),
        ('kenku', 'Kenku'),
        ('khenra', 'Khenra'),
        ('kobold', 'Kobold'),
        ('kor', 'Kor'),
        ('leonin', 'Leonin'),
        ('lizardfolk', 'Lizardfolk'),
        ('locathah', 'Locathah'),
        ('loxodon', 'Loxodon'),
        ('merfolk', 'Merfolk'),
        ('minotaur', 'Minotaur'),
        ('naga', 'Naga'),
        ('orc', 'Orc'),
        ('owlin', 'Owlin'),
        ('plasmoid', 'Plasmoid'),
        ('reborn', 'Reborn'),
        ('revenant', 'Revenant'),
        ('satyr', 'Satyr'),
        ('sea_elf', 'Sea Elf'),
        ('shadar_kai', 'Shadar-kai'),
        ('shifter', 'Shifter'),
        ('simic_hybrid', 'Simic Hybrid'),
        ('siren', 'Siren'),
        ('tabaxi', 'Tabaxi'),
        ('thri_kreen', 'Thri-kreen'),
        ('tiefling', 'Tiefling'),
        ('tortle', 'Tortle'),
        ('triton', 'Triton'),
        ('vampire', 'Vampire'),
        ('vedalken', 'Vedalken'),
        ('verdan', 'Verdan'),
        ('viashino', 'Viashino'),
        ('warforged', 'Warforged'),
        ('yuan_ti', 'Yuan-ti'),
        ('yuan_ti_pureblood', 'Yuan-ti Pureblood'),
    ]

    # Common
    name = models.CharField(max_length=100)
    race = models.CharField(max_length=50, choices=RACE_CHOICES)
    classes = models.ManyToManyField(CharacterClass, related_name='characters')
    level = models.IntegerField(default=1)
    input_method = models.CharField(max_length=20, choices=INPUT_METHOD_CHOICES, default='manual')
    created_at = models.DateTimeField(default=timezone.now)
    
    
    hit_points = models.IntegerField(default=10)
    armor_class = models.IntegerField(default=10)
    speed = models.IntegerField(default=30)  # Speed in feet per round
    strength = models.IntegerField(default=10)
    dexterity = models.IntegerField(default=10)
    constitution = models.IntegerField(default=10)
    intelligence = models.IntegerField(default=10)
    wisdom = models.IntegerField(default=10)
    charisma = models.IntegerField(default=10)

    # Abilities
    proficiency_bonus = models.IntegerField(default=2)
    inspiration = models.BooleanField(default=False)

    # Features & Traits
    features_and_traits = models.TextField(blank=True)

    # Equipment
    equipment = models.TextField(blank=True)

    # Inventory
    inventory = models.TextField(blank=True)

    # Actions
    actions = models.TextField(blank=True)

    # Bonus Actions
    bonus_actions = models.TextField(blank=True)

    # Reactions
    reactions = models.TextField(blank=True)

    # Additional Stats
    initiative = models.IntegerField(default=0)
    passive_perception = models.IntegerField(default=10)

    # Saving Throws
    saving_throws = models.TextField(blank=True)

    # Skills
    skills = models.TextField(blank=True)

    # Languages
    languages = models.TextField(blank=True)

    # Background
    background = models.CharField(max_length=100, blank=True)

    # Alignment
    alignment = models.CharField(max_length=20, blank=True)

    # Experience

a_posts/forms.py
# forms.py

from django import forms
from .models import Monster

class ManualMonsterForm(forms.ModelForm):
    class Meta:
        model = Monster
        fields = ['name', 'size', 'creature_type', 'alignment', 'armor_class', 'hit_points', 'speed', 'strength', 'dexterity', 'constitution', 'intelligence', 'wisdom', 'charisma', 'saving_throws', 'skills', 'damage_resistances', 'damage_immunities', 'condition_immunities', 'senses', 'languages', 'challenge_rating', 'experience_points', 'special_abilities', 'special_abilities_count', 'actions']
        widgets = {
            'raw_stat_block': forms.HiddenInput(),
        }

class AutomaticMonsterForm(forms.ModelForm):
    class Meta:
        model = Monster
        fields = ['raw_stat_block']
        widgets = {
            'raw_stat_block': forms.Textarea(attrs={'rows': 10, 'cols': 40}),
        }

templates/a_posts/automatic_input_form.html
<h2 class="font2 text-center text-2xl mb-4">Automatic Input Form</h2>

<form id="automatic-input-form" action="{% url 'create-monster' %}" method="post" class="max-w-md mx-auto bg-white p-6 rounded-md shadow-md" hx-post="{% url 'create-monster' %}">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <input type="hidden" id="input_method" name="input_method" value="automatic">

    
    <label for="raw-text-field">Raw Stat Block:</label>
    <textarea id="raw-text-field" name="raw_stat_block" rows="5" cols="50"></textarea>

    
        <!-- Buttons -->
        <div style="grid-column: span 2; display: flex; justify-content: space-between;">
          <a class="button secondaryAction ml-1" href="" value="Back">Back</a>
          <button type="submit" class="mt-1">Create Monster</button>
      </div>

</form>

templates/a_posts/automatic_input_form_pc.html
<h2 class="font2 text-center text-2xl mb-4">Automatic Input Form</h2>

<form id="automatic-pc-input-form" action="{% url 'create-pc' %}" method="post" class="max-w-md mx-auto bg-white p-6 rounded-md shadow-md" hx-post="{% url 'create-pc' %}">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <input type="hidden" id="input_method" name="input_method" value="automatic">

    
    <label for="raw-text-field">Upload your PDF:</label>
<!--    <textarea id="raw-text-field" name="raw_stat_block" rows="5" cols="50"></textarea> -->

    <button type="submit" class="mt-1">Create PC</button>
    <!--<button type="submit" name="create_and_add_another" value="true" class="mt-1">Create and Add Another</button>-->
    <a class="button secondaryAction ml-1" href="">Back</a>

</form>

templates/a_posts/create_monster.html
{% extends 'layouts/b.html' %}

{% block content %}

  <h1 class="text-center text-4xl mb-6">Create a Monster/NPC</h1>
  
  <div id="step1">
    <div class="text-center">
      <button type="button" onclick="showManualForm()" class="button-half" style="background-color: #F7F8FA; color: #1F2937; border-color: #F7F8FA;">Manual Input</button>
      <span style="color: #1F2937;">or</span>
      <button type="button" onclick="showAutomaticForm()" class="button-half" style="background-color: #F7F8FA; color: #1F2937; border-color: #F7F8FA;">Automatic Input</button>
    </div>
  </div>

  <div id="step2" style="display: none;"></div>

  <script>
function showManualForm() {
  document.getElementById("step1").style.display = "none";
  fetch("{% url 'manual-input-form' %}")
    .then(response => response.text())
    .then(data => {
      document.getElementById("step2").innerHTML = data;
      document.getElementById("step2").style.display = "block"; 
    });
  document.getElementById("input_method").value = "manual";
}

function showAutomaticForm() {
  document.getElementById("step1").style.display = "none";
  fetch("{% url 'automatic-input-form' %}")
    .then(response => response.text())
    .then(data => {
      document.getElementById("step2").innerHTML = data;
      document.getElementById("step2").style.display = "block";   
    });
  document.getElementById("input_method").value = "automatic";
}
  </script>


  <div class="mt-6 text-center">
    (centered text)
  </div>
  {% endblock %}

templates/a_posts/create_pc.html
{% extends 'layouts/b.html' %}

{% block content %}

  <h1 class="text-center text-4xl mb-6">Create a PC</h1>
  <p>Either input your values manually or upload a pdf</p>
  <div id="step1">
    <div class="text-center">
      <button type="button" onclick="showManualForm()" class="button-half" style="background-color: #F7F8FA; color: #1F2937; border-color: #F7F8FA;">Manual Input</button>
      <span style="color: #1F2937;">or</span>
      <button type="button" onclick="showAutomaticForm()" class="button-half" style="background-color: #F7F8FA; color: #1F2937; border-color: #F7F8FA;">Automatic Input</button>
    </div>
  </div>

  <div id="step2" style="display: none;"></div>

  <script>
function showManualForm() {
  document.getElementById("step1").style.display = "none";
  fetch("{% url 'manual-pc-input-form' %}")
    .then(response => response.text())
    .then(data => {
      document.getElementById("step2").innerHTML = data;
      document.getElementById("step2").style.display = "block"; 
    });
  document.getElementById("input_method").value = "manual";
}

function showAutomaticForm() {
  document.getElementById("step1").style.display = "none";
  fetch("{% url 'automatic-pc-input-form' %}")
    .then(response => response.text())
    .then(data => {
      document.getElementById("step2").innerHTML = data;
      document.getElementById("step2").style.display = "block";   
    });
  document.getElementById("input_method").value = "automatic";
}
  </script>


  <div class="mt-6 text-center">
    (centered text)
  </div>
  {% endblock %}

templates/a_posts/manual_input_form.html
<h2 class="font2 text-center text-2xl mb-4">Manual Input</h2>    

<form id="manual-monster-form" action="{% url 'create-monster' %}" method="post" class="max-w-xl mx-auto bg-white p-6 rounded-md shadow-md" hx-post="{% url 'create-monster' %}" style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem;">
    {% csrf_token %}
    {{ form.non_field_errors }} 

    <input type="hidden" id="input_method" name="input_method" value="manual">

    <!-- Basic Info -->
    <div style="grid-column: span 2;">
        <h3>Basic Info</h3>
        <p>
            <label for="id_name">Creature Name:</label>
            <input type="text" name="name" required>
        </p>
        <p>
            <label for="id_size">Size:</label>
            <input type="text" name="size" required="">
        </p>
        <p>
            <label for="id_creature_type">Creature Type:</label>
            <input type="text" name="creature_type" required="">
        </p>
        <p>
            <label for="id_alignment">Alignment: </label>
            <input type="text" name="alignment" required="">
        </p>
        <p>
            <label for="id_armor_class">Armor Class: </label>
            <input type="number" name="armor_class" required="">
        </p>
        <p>
            <label for="id_hit_points">Hit Points: </label>
            <input type="number" name="hit_points" required="">
        </p>
        <p>
            <label for="id_speed">Speed: </label>
            <input type="text" name="speed" required="">
        </p>
    </div>


<!-- Abilities -->
<div style="grid-column: span 2;">
    <h3>Abilities</h3>
    <table style="width: 100%;">
        <tr>
            <td><label for="id_strength">Strength:</label></td>
            <td><label for="id_dexterity">Dexterity:</label></td>
            <td><label for="id_constitution">Constitution:</label></td>
        </tr>
        <tr>
            <td><input type="number" name="strength" required></td>
            <td><input type="number" name="dexterity" required></td>
            <td><input type="number" name="constitution" required></td>
        </tr>
        <tr>
            <td><label for="id_intelligence">Intelligence:</label></td>
            <td><label for="id_wisdom">Wisdom:</label></td>
            <td><label for="id_charisma">Charisma:</label></td>
        </tr>
        <tr>
            <td><input type="number" name="intelligence" required></td>
            <td><input type="number" name="wisdom" required></td>
            <td><input type="number" name="charisma" required></td>
        </tr>
    </table>
</div>


    <!-- Traits -->
    <div>
        <h3>Traits</h3>
        <p>
            <label for="id_saving_throws">Saving Throws: </label>
            <textarea name="saving_throws"></textarea>
        </p>
        <p>
            <label for="id_skills">Skills: </label>
            <textarea name="skills"></textarea>
        </p>
        <p>
            <label for="id_damage_resistances">Damage Resistances: </label>
            <textarea name="damage_resistances"></textarea>
        </p>
        <p>
            <label for="id_damage_immunities">Damage Immunities: </label>
            <textarea name="damage_immunities"></textarea>
        </p>
        <p>
            <label for="id_condition_immunities">Condition Immunities: </label>
            <textarea name="condition_immunities"></textarea>
        </p>
        <p>
            <label for="id_senses">Senses: </label>
            <textarea name="senses"></textarea>
        </p>
        <p>
            <label for="id_languages">Languages: </label>
            <textarea name="languages"></textarea>
        </p>
    </div>

    <!-- Challenge and Experience -->
    <div>
        <h3>Challenge and Experience</h3>
        <p>
            <label for="id_challenge_rating">Challenge Rating: </label>
            <input type="number" name="challenge_rating" step="0.1" required="">
        </p>
        <p>
            <label for="id_experience_points">Experience Points: </label>
            <input type="number" name="experience_points">
        </p>
    </div>

    <!-- Actions -->
    <div style="grid-column: span 2;">
        <h3>Actions</h3>
        <p>
            <label for="id_actions">Actions: </label>
            <textarea name="actions"></textarea>
        </p>
        <p>
            <label for="id_special_abilities">Special Abilities: </label>
            <textarea name="special_abilities"></textarea>
        </p>
        <p>
            <label for="id_special_abilities_count">Special Abilities Count: </label>
            <input type="number" name="special_abilities_count">
        </p>
    </div>
    
        <!-- Buttons -->
        <div style="grid-column: span 2; display: flex; justify-content: space-between;">
            <a class="button secondaryAction ml-1" href="" value="Back">Back</a>
            <button type="submit" class="mt-1">Create Monster</button>
        </div>
    </form>
    

templates/a_posts/manual_pc_input_form.html
<h2 class="font2 text-center text-2xl mb-4" style="grid-column: span 2;">Manual Input</h2>
<p style="grid-column: span 2;">This form is a bit comprehensive and it's recommended you try <a href="automatic_input_form_pc.html">importing a pdf</a> if you're able.</p>
<form id="manual-pc-form" action="{% url 'create-pc' %}" method="post" class="max-w-md mx-auto bg-white p-6 rounded-md shadow-md" hx-post="{% url 'create-pc' %}" style="display: grid; grid-template-columns: 1fr 1fr; gap: 1rem;">
    {% csrf_token %}
    {{ form.non_field_errors }} 

    <input type="hidden" id="input_method" name="input_method" value="manual">

    <!-- Basic Info -->
    <div style="grid-column: span 2;">
        <h3>Basic Info</h3>
        <p>
            <label for="id_name">Character Name:</label>
            <input type="text" name="name" required>
        </p>
        <p>
            <label for="id_player_name">Player Name:</label>
            <input type="text" name="player_name" required>
        </p>
        <p>
            <label for="id_size">Size:</label>
            <input type="text" name="size" required>
        </p>
        <p>
            <label for="id_creature_type">Creature Type:</label>
            <input type="text" name="creature_type" required>
        </p>
        <p>
            <label for="id_alignment">Alignment:</label>
            <input type="text" name="alignment" required>
        </p>
        <p>
            <label for="id_armor_class">Armor Class:</label>
            <input type="number" name="armor_class" required>
        </p>
        <p>
            <label for="id_hit_points">Hit Points:</label>
            <input type="number" name="hit_points" required>
        </p>
        <p>
            <label for="id_speed">Speed:</label>
            <input type="text" name="speed" required>
        </p>
    </div>

    <!-- Abilities -->
    <div>
        <h3>Abilities</h3>
        <p>
            <label for="id_strength">Strength:</label>
            <input type="number" name="strength" required>
        </p>
        <p>
            <label for="id_dexterity">Dexterity:</label>
            <input type="number" name="dexterity" required>
        </p>
        <p>
            <label for="id_constitution">Constitution:</label>
            <input type="number" name="constitution" required>
        </p>
        <p>
            <label for="id_intelligence">Intelligence:</label>
            <input type="number" name="intelligence" required>
        </p>
        <p>
            <label for="id_wisdom">Wisdom:</label>
            <input type="number" name="wisdom" required>
        </p>
        <p>
            <label for="id_charisma">Charisma:</label>
            <input type="number" name="charisma" required>
        </p>
    </div>

    <!-- Proficiency and Inspiration -->
    <div>
        <h3>Proficiency and Inspiration</h3>
        <p>
            <label for="id_proficiency_bonus">Proficiency Bonus:</label>
            <input type="number" name="proficiency_bonus" required>
        </p>
        <p>
            <label for="id_inspiration">Inspiration:</label>
            <input type="checkbox" name="inspiration">
        </p>
    </div>

    <!-- Features, Equipment, and Inventory -->
    <div>
        <h3>Features, Equipment, and Inventory</h3>
        <p>
            <label for="id_features_and_traits">Features & Traits:</label>
            <textarea name="features_and_traits"></textarea>
        </p>
        <p>
            <label for="id_equipment">Equipment:</label>
            <textarea name="equipment"></textarea>
        </p>
        <p>
            <label for="id_inventory">Inventory:</label>
            <textarea name="inventory"></textarea>
        </p>
    </div>

    <!-- Actions -->
    <div>
        <h3>Actions</h3>
        <p>
            <label for="id_actions">Actions:</label>
            <textarea name="actions"></textarea>
        </p>
        <p>
            <label for="id_bonus_actions">Bonus Actions:</label>
            <textarea name="bonus_actions"></textarea>
        </p>
        <p>
            <label for="id_reactions">Reactions:</label>
            <textarea name="reactions"></textarea>
        </p>
    </div>

    <!-- Initiative and Passive Perception -->
    <div>
        <h3>Initiative and Passive Perception</h3>
        <p>
            <label for="id_initiative">Initiative:</label>
            <input type="number" name="initiative" required>
        </p>
        <p>
            <label for="id_passive_perception">Passive Perception:</label>
            <input type="number" name="passive_perception" required>
        </p>
    </div>

    <!-- Saving Throws, Skills, Languages, Background, and Experience -->
    <div style="grid-column: span 2;">
        <h3>Saving Throws, Skills, Languages, Background, and Experience</h3>
        <p>
            <label for="id_saving_throws">Saving Throws:</label>
            <textarea name="saving_throws"></textarea>
        </p>
        <p>
            <label for="id_skills">Skills:</label>
            <textarea name="skills"></textarea>
        </p>
        <p>
            <label for="id_languages">Languages:</label>
            <textarea name="languages"></textarea>
        </p>
        <p>
            <label for="id_background">Background:</label>
            <input type="text" name="background">
        </p>
        <p>
            <label for="id_experience_points">Experience Points:</label>
            <input type="number" name="experience_points">
        </p>
    </div>

    <button type="submit" class="mt-1" style="grid-column: span 2;">Create PC</button>
    <!--<button type="submit" name="create_and_add_another" value="true" class="mt-1">Create and Add Another</button>-->
    <a class="button secondaryAction ml-1" href="" value="Back" style="grid-column: span 2;">Back</a>

</form>

templates/a_posts/post_create.html
<! -- 

Example of a form

{% extends 'layouts/b.html' %}

{% block content %}
<h1>Create Post</h1>
<div class="card !p-8">
    
    <div class="flex items-center mb-6">
        <img class="h-5 object-cover mr-1" src="https://img.icons8.com/small/96/333333/search--v1.png"/>
        <a href="https://www.flickr.com/explore" target="_blank" class="hover:underline text-gray-500">Find an image on Flickr</a>
    </div>

    <form method='POST'>
        <p>
            <label>Image:</label>
            <input required="" >
        </p>
        <p>
            <label for="id_title">Title:</label>
            <input required="" >
        </p>
        <p>
            <label for="id_artist">Artist:</label>
            <input required="" >
        </p>
        <button type="submit" class="mt-1">Submit Post</button>
        <a class="button secondaryAction ml-1" href="">Cancel</a>
    </form>
</div>
{% endblock %}

-->